/* eslint-disable no-unused-vars */
/**
 * Error codes for categorizing different kinds of exceptions.
 */
export enum ErrorCode {
    FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
    NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
    CONFLICT_ERROR = 'CONFLICT_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    SCHEMA_VALIDATION_ERROR = 'SCHEMA_VALIDATION_ERROR',
    BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    DATABASE_OPERATION_FAILED_ERROR = 'DATABASE_OPERATION_FAILED_ERROR',
    JOBS_FAILED_TO_SCHEDULE_JOB = 'JOBS_FAILED_TO_SCHEDULE_JOB',
    JOBS_FAILED_TO_DELEGATE_JOB = 'JOBS_FAILED_TO_DELEGATE_JOB',
}
