/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobTargetFinishedEvent } from './jobTargetFinishedEvent';

export interface AggregatedRunningJob {
  emittedEvents: JobTargetFinishedEvent[];
  jobId: string;
}
