/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { AggregatedRunningJob } from './aggregatedRunningJob';
import type { ScheduledJobEvent } from './scheduledJobEvent';
import type { AggregatedJobsEventType } from './aggregatedJobsEventType';

export interface AggregatedJobsEvent {
  runningJobs: AggregatedRunningJob[];
  scheduledJobs: ScheduledJobEvent[];
  type: AggregatedJobsEventType;
  userId: string;
}
