/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type AggregatedJobsEventType = typeof AggregatedJobsEventType[keyof typeof AggregatedJobsEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AggregatedJobsEventType = {
  'jobs-aggregated': 'jobs-aggregated',
} as const;
