/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTargetListing } from './executionScraperToolTargetListing';
import type { ExecutionScraperToolTargetMatch } from './executionScraperToolTargetMatch';
import type { ExecutionScraperToolTargetScreen } from './executionScraperToolTargetScreen';

export interface ExecutionScraperToolTargetResult {
  listing: ExecutionScraperToolTargetListing;
  match?: ExecutionScraperToolTargetMatch;
  screen?: ExecutionScraperToolTargetScreen;
}
