/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTargetListingError } from './executionScraperToolTargetListingError';
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ExecutionScraperToolTargetListingFail {
  error: ExecutionScraperToolTargetListingError;
  ok: boolean;
  source: ScraperToolTargetName;
  /** @nullable */
  url: string | null;
}
