/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTargetListingSuccessFields } from './executionScraperToolTargetListingSuccessFields';
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ExecutionScraperToolTargetListingSuccess {
  fields?: ExecutionScraperToolTargetListingSuccessFields;
  ok: boolean;
  /** @nullable */
  postedAt?: string | null;
  source: ScraperToolTargetName;
  text: string;
  title: string;
  url: string;
}
