/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTargetSummaryReasonCounts } from './executionScraperToolTargetSummaryReasonCounts';

export interface ExecutionScraperToolTargetSummary {
  passed: number;
  reasonCounts: ExecutionScraperToolTargetSummaryReasonCounts;
  rejected: number;
  total: number;
}
