/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTargetResult } from './executionScraperToolTargetResult';
import type { ExecutionScraperToolTargetSummary } from './executionScraperToolTargetSummary';
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ExecutionScraperToolTarget {
  /** @minItems 1 */
  keywords?: string[];
  /** @minimum 0 */
  maxPages?: number;
  results: ExecutionScraperToolTargetResult[];
  summary: ExecutionScraperToolTargetSummary;
  target: ScraperToolTargetName;
  targetId: string;
}
