/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobCancelledEventType } from './jobCancelledEventType';

export interface JobCancelledEvent {
  cancelledAt: string;
  executionId: string;
  jobId: string;
  type: JobCancelledEventType;
  userId: string;
}
