/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobTargetFinishedEvent } from './jobTargetFinishedEvent';
import type { AggregatedJobsEvent } from './aggregatedJobsEvent';
import type { RunningJobsEvent } from './runningJobsEvent';
import type { ScheduledJobsEvent } from './scheduledJobsEvent';
import type { JobFinishedEvent } from './jobFinishedEvent';
import type { JobFailedEvent } from './jobFailedEvent';
import type { JobCancelledEvent } from './jobCancelledEvent';

export type JobEvent = JobTargetFinishedEvent | AggregatedJobsEvent | RunningJobsEvent | ScheduledJobsEvent | JobFinishedEvent | JobFailedEvent | JobCancelledEvent;
