/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type JobScheduleStatus = typeof JobScheduleStatus[keyof typeof JobScheduleStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobScheduleStatus = {
  idle: 'idle',
  stopped: 'stopped',
} as const;
