/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduledJobEvent } from './scheduledJobEvent';
import type { ScheduledJobsEventType } from './scheduledJobsEventType';

export interface ScheduledJobsEvent {
  scheduledJobs: ScheduledJobEvent[];
  type: ScheduledJobsEventType;
  userId: string;
}
